packages:
  - "packages/core"
  - "packages/ui"
  - "packages/sandbox"
  - "packages/benchmark"
  - "packages/vuelib"
  - "packages/vuelib-tailwind4"
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  husky: true

minimumReleaseAge: 1440
