import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { generateSafeList } from "@busbud/tailwind-buddy";

import { buttonVariants } from "../src/components/Button/Button.variants";
import { labelVariants } from "../src/components/Label/Label.variants";
import { screens } from "../src/tailwind-buddy-interface";

/**
 * tailwind-buddy composes some class names at runtime (responsive variants),
 * so they never appear literally in the source Tailwind scans. In Tailwind v4
 * the `safelist` config option is gone; the replacement is `@source inline()`.
 *
 * This script runs generateSafeList and bakes the result into a shipped CSS
 * partial. ui-kit (the library) owns this list; consumers just import the
 * partial and inherit it — the same way an app consumes a component library's
 * baked-in `@source inline` in v4.
 */
const classes = generateSafeList([labelVariants, buttonVariants], screens);

const banner = "/* Generated by scripts/generate-safelist.ts — do not edit by hand. */";
const css = `${banner}\n@source inline("{${classes.join(",")}}");\n`;

const out = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/generated/safelist.css"
);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css);

console.log(`Wrote ${classes.length} safelisted classes to ${out}`);
