
interface _GlobalComponents {
      'Alert': typeof import("../components/content/Alert.vue")['default']
    'Badge': typeof import("../components/content/Badge.vue")['default']
    'Callout': typeof import("../components/content/Callout.vue")['default']
    'Card': typeof import("../components/content/Card.vue")['default']
    'CardGroup': typeof import("../components/content/CardGroup.vue")['default']
    'CodeCopy': typeof import("../components/content/CodeCopy.vue")['default']
    'CodeGroup': typeof import("../components/content/CodeGroup.vue")['default']
    'Field': typeof import("../components/content/Field.vue")['default']
    'FieldGroup': typeof import("../components/content/FieldGroup.vue")['default']
    'Hero': typeof import("../components/content/Hero.vue")['default']
    'Kbd': typeof import("../components/content/Kbd.vue")['default']
    'ProseA': typeof import("../components/content/ProseA.vue")['default']
    'ProseBlockquote': typeof import("../components/content/ProseBlockquote.vue")['default']
    'ProseCode': typeof import("../components/content/ProseCode.vue")['default']
    'ProseCodeInline': typeof import("../components/content/ProseCodeInline.vue")['default']
    'ProseEm': typeof import("../components/content/ProseEm.vue")['default']
    'ProseH1': typeof import("../components/content/ProseH1.vue")['default']
    'ProseH2': typeof import("../components/content/ProseH2.vue")['default']
    'ProseH3': typeof import("../components/content/ProseH3.vue")['default']
    'ProseH4': typeof import("../components/content/ProseH4.vue")['default']
    'ProseH5': typeof import("../components/content/ProseH5.vue")['default']
    'ProseH6': typeof import("../components/content/ProseH6.vue")['default']
    'ProseHr': typeof import("../components/content/ProseHr.vue")['default']
    'ProseImg': typeof import("../components/content/ProseImg.vue")['default']
    'ProseLi': typeof import("../components/content/ProseLi.vue")['default']
    'ProseOl': typeof import("../components/content/ProseOl.vue")['default']
    'ProseP': typeof import("../components/content/ProseP.vue")['default']
    'ProsePre': typeof import("../components/content/ProsePre.vue")['default']
    'ProseStrong': typeof import("../components/content/ProseStrong.vue")['default']
    'ProseTable': typeof import("../components/content/ProseTable.vue")['default']
    'ProseTbody': typeof import("../components/content/ProseTbody.vue")['default']
    'ProseTd': typeof import("../components/content/ProseTd.vue")['default']
    'ProseTh': typeof import("../components/content/ProseTh.vue")['default']
    'ProseThead': typeof import("../components/content/ProseThead.vue")['default']
    'ProseTr': typeof import("../components/content/ProseTr.vue")['default']
    'ProseUl': typeof import("../components/content/ProseUl.vue")['default']
    'ReadMore': typeof import("../components/content/ReadMore.vue")['default']
    'Steps': typeof import("../components/content/Steps.vue")['default']
    'Tabs': typeof import("../components/content/Tabs.vue")['default']
    'DarkModeToggle': typeof import("../components/DarkModeToggle.vue")['default']
    'LayoutAside': typeof import("../components/layout/Aside.vue")['default']
    'LayoutAsideTree': typeof import("../components/layout/AsideTree.vue")['default']
    'LayoutAsideTreeItem': typeof import("../components/layout/AsideTreeItem.vue")['default']
    'LayoutBreadcrumb': typeof import("../components/layout/Breadcrumb.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LayoutHeaderLogo': typeof import("../components/layout/Header/Logo.vue")['default']
    'LayoutHeaderNav': typeof import("../components/layout/Header/Nav.vue")['default']
    'LayoutHeaderNavMobile': typeof import("../components/layout/Header/NavMobile.vue")['default']
    'LayoutHeaderNavMobileItem': typeof import("../components/layout/Header/NavMobileItem.vue")['default']
    'LayoutMobileNav': typeof import("../components/layout/MobileNav.vue")['default']
    'LayoutPrevNext': typeof import("../components/layout/PrevNext.vue")['default']
    'LayoutPrevNextButton': typeof import("../components/layout/PrevNextButton.vue")['default']
    'LayoutSearchButton': typeof import("../components/layout/SearchButton.vue")['default']
    'LayoutSearchDialog': typeof import("../components/layout/SearchDialog.vue")['default']
    'LayoutToc': typeof import("../components/layout/Toc.vue")['default']
    'LayoutTocTree': typeof import("../components/layout/TocTree.vue")['default']
    'UiAlert': typeof import("../components/ui/alert/index")['Alert']
    'UiAlertDescription': typeof import("../components/ui/alert/index")['AlertDescription']
    'UiAlertTitle': typeof import("../components/ui/alert/index")['AlertTitle']
    'UiBadge': typeof import("../components/ui/badge/index")['Badge']
    'UiBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'UiBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'UiBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'UiBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'UiBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'UiBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'UiBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'UiButton': typeof import("../components/ui/button/index")['Button']
    'UiCard': typeof import("../components/ui/card/index")['Card']
    'UiCardContent': typeof import("../components/ui/card/index")['CardContent']
    'UiCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'UiCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'UiCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'UiCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'UiCollapsible': typeof import("../components/ui/collapsible/index")['Collapsible']
    'UiCollapsibleContent': typeof import("../components/ui/collapsible/index")['CollapsibleContent']
    'UiCollapsibleTrigger': typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
    'UiCommand': typeof import("../components/ui/command/index")['Command']
    'UiCommandDialog': typeof import("../components/ui/command/index")['CommandDialog']
    'UiCommandEmpty': typeof import("../components/ui/command/index")['CommandEmpty']
    'UiCommandGroup': typeof import("../components/ui/command/index")['CommandGroup']
    'UiCommandInput': typeof import("../components/ui/command/index")['CommandInput']
    'UiCommandItem': typeof import("../components/ui/command/index")['CommandItem']
    'UiCommandList': typeof import("../components/ui/command/index")['CommandList']
    'UiCommandSeparator': typeof import("../components/ui/command/index")['CommandSeparator']
    'UiCommandShortcut': typeof import("../components/ui/command/index")['CommandShortcut']
    'UiDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'UiDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'UiDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'UiDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'UiDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'UiDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'UiDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'UiDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'UiDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'UiDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'UiDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'UiDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'UiDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'UiDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'UiDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'UiDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'UiDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'UiDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'UiDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'UiDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'UiDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'UiDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'UiDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'UiNavigationMenu': typeof import("../components/ui/navigation-menu/index")['NavigationMenu']
    'UiNavigationMenuContent': typeof import("../components/ui/navigation-menu/index")['NavigationMenuContent']
    'UiNavigationMenuIndicator': typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuIndicator.vue")['default']
    'UiNavigationMenuItem': typeof import("../components/ui/navigation-menu/index")['NavigationMenuItem']
    'UiNavigationMenuLink': typeof import("../components/ui/navigation-menu/index")['NavigationMenuLink']
    'UiNavigationMenuList': typeof import("../components/ui/navigation-menu/index")['NavigationMenuList']
    'UiNavigationMenuTrigger': typeof import("../components/ui/navigation-menu/index")['NavigationMenuTrigger']
    'UiNavigationMenuViewport': typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuViewport.vue")['default']
    'UiScrollArea': typeof import("../components/ui/scroll-area/index")['ScrollArea']
    'UiScrollAreaScrollBar': typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/scroll-area/ScrollBar.vue")['default']
    'UiSeparator': typeof import("../components/ui/separator/index")['Separator']
    'UiSheet': typeof import("../components/ui/sheet/index")['Sheet']
    'UiSheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'UiSheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'UiSheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'UiSheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'UiSheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'UiSheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'UiSheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'UiTabs': typeof import("../components/ui/tabs/index")['Tabs']
    'UiTabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'UiTabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'UiTabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'ContentDoc': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'ContentList': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'ContentNavigation': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'ContentQuery': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'ContentRenderer': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'ContentRendererMarkdown': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'ContentSlot': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'DocumentDrivenEmpty': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'DocumentDrivenNotFound': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'Markdown': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'ProseScript': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'NuxtWelcome': typeof import("../../../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'UiDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'UiScrollBar': typeof import("../components/ui/scroll-area/index")['ScrollBar']
    'MDC': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
    'MDCRenderer': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
    'MDCSlot': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
    'Icon': typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAlert': typeof import("../components/content/Alert.vue")['default']
    'LazyBadge': typeof import("../components/content/Badge.vue")['default']
    'LazyCallout': typeof import("../components/content/Callout.vue")['default']
    'LazyCard': typeof import("../components/content/Card.vue")['default']
    'LazyCardGroup': typeof import("../components/content/CardGroup.vue")['default']
    'LazyCodeCopy': typeof import("../components/content/CodeCopy.vue")['default']
    'LazyCodeGroup': typeof import("../components/content/CodeGroup.vue")['default']
    'LazyField': typeof import("../components/content/Field.vue")['default']
    'LazyFieldGroup': typeof import("../components/content/FieldGroup.vue")['default']
    'LazyHero': typeof import("../components/content/Hero.vue")['default']
    'LazyKbd': typeof import("../components/content/Kbd.vue")['default']
    'LazyProseA': typeof import("../components/content/ProseA.vue")['default']
    'LazyProseBlockquote': typeof import("../components/content/ProseBlockquote.vue")['default']
    'LazyProseCode': typeof import("../components/content/ProseCode.vue")['default']
    'LazyProseCodeInline': typeof import("../components/content/ProseCodeInline.vue")['default']
    'LazyProseEm': typeof import("../components/content/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../components/content/ProseH1.vue")['default']
    'LazyProseH2': typeof import("../components/content/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../components/content/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../components/content/ProseH4.vue")['default']
    'LazyProseH5': typeof import("../components/content/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../components/content/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../components/content/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../components/content/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../components/content/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../components/content/ProseOl.vue")['default']
    'LazyProseP': typeof import("../components/content/ProseP.vue")['default']
    'LazyProsePre': typeof import("../components/content/ProsePre.vue")['default']
    'LazyProseStrong': typeof import("../components/content/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../components/content/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../components/content/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../components/content/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../components/content/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../components/content/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../components/content/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../components/content/ProseUl.vue")['default']
    'LazyReadMore': typeof import("../components/content/ReadMore.vue")['default']
    'LazySteps': typeof import("../components/content/Steps.vue")['default']
    'LazyTabs': typeof import("../components/content/Tabs.vue")['default']
    'LazyDarkModeToggle': typeof import("../components/DarkModeToggle.vue")['default']
    'LazyLayoutAside': typeof import("../components/layout/Aside.vue")['default']
    'LazyLayoutAsideTree': typeof import("../components/layout/AsideTree.vue")['default']
    'LazyLayoutAsideTreeItem': typeof import("../components/layout/AsideTreeItem.vue")['default']
    'LazyLayoutBreadcrumb': typeof import("../components/layout/Breadcrumb.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LazyLayoutHeaderLogo': typeof import("../components/layout/Header/Logo.vue")['default']
    'LazyLayoutHeaderNav': typeof import("../components/layout/Header/Nav.vue")['default']
    'LazyLayoutHeaderNavMobile': typeof import("../components/layout/Header/NavMobile.vue")['default']
    'LazyLayoutHeaderNavMobileItem': typeof import("../components/layout/Header/NavMobileItem.vue")['default']
    'LazyLayoutMobileNav': typeof import("../components/layout/MobileNav.vue")['default']
    'LazyLayoutPrevNext': typeof import("../components/layout/PrevNext.vue")['default']
    'LazyLayoutPrevNextButton': typeof import("../components/layout/PrevNextButton.vue")['default']
    'LazyLayoutSearchButton': typeof import("../components/layout/SearchButton.vue")['default']
    'LazyLayoutSearchDialog': typeof import("../components/layout/SearchDialog.vue")['default']
    'LazyLayoutToc': typeof import("../components/layout/Toc.vue")['default']
    'LazyLayoutTocTree': typeof import("../components/layout/TocTree.vue")['default']
    'LazyUiAlert': typeof import("../components/ui/alert/index")['Alert']
    'LazyUiAlertDescription': typeof import("../components/ui/alert/index")['AlertDescription']
    'LazyUiAlertTitle': typeof import("../components/ui/alert/index")['AlertTitle']
    'LazyUiBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyUiBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyUiBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyUiBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyUiBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyUiBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyUiBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyUiBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyUiButton': typeof import("../components/ui/button/index")['Button']
    'LazyUiCard': typeof import("../components/ui/card/index")['Card']
    'LazyUiCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyUiCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyUiCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyUiCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyUiCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyUiCollapsible': typeof import("../components/ui/collapsible/index")['Collapsible']
    'LazyUiCollapsibleContent': typeof import("../components/ui/collapsible/index")['CollapsibleContent']
    'LazyUiCollapsibleTrigger': typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
    'LazyUiCommand': typeof import("../components/ui/command/index")['Command']
    'LazyUiCommandDialog': typeof import("../components/ui/command/index")['CommandDialog']
    'LazyUiCommandEmpty': typeof import("../components/ui/command/index")['CommandEmpty']
    'LazyUiCommandGroup': typeof import("../components/ui/command/index")['CommandGroup']
    'LazyUiCommandInput': typeof import("../components/ui/command/index")['CommandInput']
    'LazyUiCommandItem': typeof import("../components/ui/command/index")['CommandItem']
    'LazyUiCommandList': typeof import("../components/ui/command/index")['CommandList']
    'LazyUiCommandSeparator': typeof import("../components/ui/command/index")['CommandSeparator']
    'LazyUiCommandShortcut': typeof import("../components/ui/command/index")['CommandShortcut']
    'LazyUiDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyUiDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyUiDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyUiDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyUiDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyUiDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyUiDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyUiDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyUiDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyUiDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyUiDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyUiDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyUiDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyUiDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyUiDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyUiDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyUiDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyUiDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyUiDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyUiDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyUiDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyUiDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyUiDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyUiNavigationMenu': typeof import("../components/ui/navigation-menu/index")['NavigationMenu']
    'LazyUiNavigationMenuContent': typeof import("../components/ui/navigation-menu/index")['NavigationMenuContent']
    'LazyUiNavigationMenuIndicator': typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuIndicator.vue")['default']
    'LazyUiNavigationMenuItem': typeof import("../components/ui/navigation-menu/index")['NavigationMenuItem']
    'LazyUiNavigationMenuLink': typeof import("../components/ui/navigation-menu/index")['NavigationMenuLink']
    'LazyUiNavigationMenuList': typeof import("../components/ui/navigation-menu/index")['NavigationMenuList']
    'LazyUiNavigationMenuTrigger': typeof import("../components/ui/navigation-menu/index")['NavigationMenuTrigger']
    'LazyUiNavigationMenuViewport': typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuViewport.vue")['default']
    'LazyUiScrollArea': typeof import("../components/ui/scroll-area/index")['ScrollArea']
    'LazyUiScrollAreaScrollBar': typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/scroll-area/ScrollBar.vue")['default']
    'LazyUiSeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazyUiSheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazyUiSheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazyUiSheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazyUiSheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazyUiSheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazyUiSheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazyUiSheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazyUiSheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazyUiTabs': typeof import("../components/ui/tabs/index")['Tabs']
    'LazyUiTabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'LazyUiTabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'LazyUiTabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'LazyContentDoc': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'LazyContentList': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'LazyContentNavigation': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'LazyContentQuery': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'LazyContentRenderer': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'LazyContentRendererMarkdown': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'LazyContentSlot': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'LazyDocumentDrivenEmpty': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'LazyDocumentDrivenNotFound': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'LazyMarkdown': typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'LazyProseScript': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyUiDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyUiScrollBar': typeof import("../components/ui/scroll-area/index")['ScrollBar']
    'LazyMDC': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
    'LazyMDCRenderer': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
    'LazyMDCSlot': typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
    'LazyIcon': typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Alert: typeof import("../components/content/Alert.vue")['default']
export const Badge: typeof import("../components/content/Badge.vue")['default']
export const Callout: typeof import("../components/content/Callout.vue")['default']
export const Card: typeof import("../components/content/Card.vue")['default']
export const CardGroup: typeof import("../components/content/CardGroup.vue")['default']
export const CodeCopy: typeof import("../components/content/CodeCopy.vue")['default']
export const CodeGroup: typeof import("../components/content/CodeGroup.vue")['default']
export const Field: typeof import("../components/content/Field.vue")['default']
export const FieldGroup: typeof import("../components/content/FieldGroup.vue")['default']
export const Hero: typeof import("../components/content/Hero.vue")['default']
export const Kbd: typeof import("../components/content/Kbd.vue")['default']
export const ProseA: typeof import("../components/content/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../components/content/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../components/content/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../components/content/ProseCodeInline.vue")['default']
export const ProseEm: typeof import("../components/content/ProseEm.vue")['default']
export const ProseH1: typeof import("../components/content/ProseH1.vue")['default']
export const ProseH2: typeof import("../components/content/ProseH2.vue")['default']
export const ProseH3: typeof import("../components/content/ProseH3.vue")['default']
export const ProseH4: typeof import("../components/content/ProseH4.vue")['default']
export const ProseH5: typeof import("../components/content/ProseH5.vue")['default']
export const ProseH6: typeof import("../components/content/ProseH6.vue")['default']
export const ProseHr: typeof import("../components/content/ProseHr.vue")['default']
export const ProseImg: typeof import("../components/content/ProseImg.vue")['default']
export const ProseLi: typeof import("../components/content/ProseLi.vue")['default']
export const ProseOl: typeof import("../components/content/ProseOl.vue")['default']
export const ProseP: typeof import("../components/content/ProseP.vue")['default']
export const ProsePre: typeof import("../components/content/ProsePre.vue")['default']
export const ProseStrong: typeof import("../components/content/ProseStrong.vue")['default']
export const ProseTable: typeof import("../components/content/ProseTable.vue")['default']
export const ProseTbody: typeof import("../components/content/ProseTbody.vue")['default']
export const ProseTd: typeof import("../components/content/ProseTd.vue")['default']
export const ProseTh: typeof import("../components/content/ProseTh.vue")['default']
export const ProseThead: typeof import("../components/content/ProseThead.vue")['default']
export const ProseTr: typeof import("../components/content/ProseTr.vue")['default']
export const ProseUl: typeof import("../components/content/ProseUl.vue")['default']
export const ReadMore: typeof import("../components/content/ReadMore.vue")['default']
export const Steps: typeof import("../components/content/Steps.vue")['default']
export const Tabs: typeof import("../components/content/Tabs.vue")['default']
export const DarkModeToggle: typeof import("../components/DarkModeToggle.vue")['default']
export const LayoutAside: typeof import("../components/layout/Aside.vue")['default']
export const LayoutAsideTree: typeof import("../components/layout/AsideTree.vue")['default']
export const LayoutAsideTreeItem: typeof import("../components/layout/AsideTreeItem.vue")['default']
export const LayoutBreadcrumb: typeof import("../components/layout/Breadcrumb.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LayoutHeaderLogo: typeof import("../components/layout/Header/Logo.vue")['default']
export const LayoutHeaderNav: typeof import("../components/layout/Header/Nav.vue")['default']
export const LayoutHeaderNavMobile: typeof import("../components/layout/Header/NavMobile.vue")['default']
export const LayoutHeaderNavMobileItem: typeof import("../components/layout/Header/NavMobileItem.vue")['default']
export const LayoutMobileNav: typeof import("../components/layout/MobileNav.vue")['default']
export const LayoutPrevNext: typeof import("../components/layout/PrevNext.vue")['default']
export const LayoutPrevNextButton: typeof import("../components/layout/PrevNextButton.vue")['default']
export const LayoutSearchButton: typeof import("../components/layout/SearchButton.vue")['default']
export const LayoutSearchDialog: typeof import("../components/layout/SearchDialog.vue")['default']
export const LayoutToc: typeof import("../components/layout/Toc.vue")['default']
export const LayoutTocTree: typeof import("../components/layout/TocTree.vue")['default']
export const UiAlert: typeof import("../components/ui/alert/index")['Alert']
export const UiAlertDescription: typeof import("../components/ui/alert/index")['AlertDescription']
export const UiAlertTitle: typeof import("../components/ui/alert/index")['AlertTitle']
export const UiBadge: typeof import("../components/ui/badge/index")['Badge']
export const UiBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const UiBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const UiBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const UiBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const UiBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const UiBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const UiBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const UiButton: typeof import("../components/ui/button/index")['Button']
export const UiCard: typeof import("../components/ui/card/index")['Card']
export const UiCardContent: typeof import("../components/ui/card/index")['CardContent']
export const UiCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const UiCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const UiCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const UiCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const UiCollapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const UiCollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const UiCollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const UiCommand: typeof import("../components/ui/command/index")['Command']
export const UiCommandDialog: typeof import("../components/ui/command/index")['CommandDialog']
export const UiCommandEmpty: typeof import("../components/ui/command/index")['CommandEmpty']
export const UiCommandGroup: typeof import("../components/ui/command/index")['CommandGroup']
export const UiCommandInput: typeof import("../components/ui/command/index")['CommandInput']
export const UiCommandItem: typeof import("../components/ui/command/index")['CommandItem']
export const UiCommandList: typeof import("../components/ui/command/index")['CommandList']
export const UiCommandSeparator: typeof import("../components/ui/command/index")['CommandSeparator']
export const UiCommandShortcut: typeof import("../components/ui/command/index")['CommandShortcut']
export const UiDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const UiDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const UiDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const UiDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const UiDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const UiDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const UiDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const UiDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const UiDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const UiDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const UiDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const UiDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const UiDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const UiDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const UiDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const UiDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const UiDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const UiDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const UiDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const UiDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const UiDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const UiDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const UiDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const UiNavigationMenu: typeof import("../components/ui/navigation-menu/index")['NavigationMenu']
export const UiNavigationMenuContent: typeof import("../components/ui/navigation-menu/index")['NavigationMenuContent']
export const UiNavigationMenuIndicator: typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuIndicator.vue")['default']
export const UiNavigationMenuItem: typeof import("../components/ui/navigation-menu/index")['NavigationMenuItem']
export const UiNavigationMenuLink: typeof import("../components/ui/navigation-menu/index")['NavigationMenuLink']
export const UiNavigationMenuList: typeof import("../components/ui/navigation-menu/index")['NavigationMenuList']
export const UiNavigationMenuTrigger: typeof import("../components/ui/navigation-menu/index")['NavigationMenuTrigger']
export const UiNavigationMenuViewport: typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuViewport.vue")['default']
export const UiScrollArea: typeof import("../components/ui/scroll-area/index")['ScrollArea']
export const UiScrollAreaScrollBar: typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/scroll-area/ScrollBar.vue")['default']
export const UiSeparator: typeof import("../components/ui/separator/index")['Separator']
export const UiSheet: typeof import("../components/ui/sheet/index")['Sheet']
export const UiSheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const UiSheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const UiSheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const UiSheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const UiSheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const UiSheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const UiSheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const UiTabs: typeof import("../components/ui/tabs/index")['Tabs']
export const UiTabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const UiTabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const UiTabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const ContentDoc: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const DocumentDrivenEmpty: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const DocumentDrivenNotFound: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const Markdown: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProseScript: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const UiDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const UiScrollBar: typeof import("../components/ui/scroll-area/index")['ScrollBar']
export const MDC: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
export const MDCRenderer: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
export const MDCSlot: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
export const Icon: typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAlert: typeof import("../components/content/Alert.vue")['default']
export const LazyBadge: typeof import("../components/content/Badge.vue")['default']
export const LazyCallout: typeof import("../components/content/Callout.vue")['default']
export const LazyCard: typeof import("../components/content/Card.vue")['default']
export const LazyCardGroup: typeof import("../components/content/CardGroup.vue")['default']
export const LazyCodeCopy: typeof import("../components/content/CodeCopy.vue")['default']
export const LazyCodeGroup: typeof import("../components/content/CodeGroup.vue")['default']
export const LazyField: typeof import("../components/content/Field.vue")['default']
export const LazyFieldGroup: typeof import("../components/content/FieldGroup.vue")['default']
export const LazyHero: typeof import("../components/content/Hero.vue")['default']
export const LazyKbd: typeof import("../components/content/Kbd.vue")['default']
export const LazyProseA: typeof import("../components/content/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../components/content/ProseBlockquote.vue")['default']
export const LazyProseCode: typeof import("../components/content/ProseCode.vue")['default']
export const LazyProseCodeInline: typeof import("../components/content/ProseCodeInline.vue")['default']
export const LazyProseEm: typeof import("../components/content/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../components/content/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../components/content/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../components/content/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../components/content/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../components/content/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../components/content/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../components/content/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../components/content/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../components/content/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../components/content/ProseOl.vue")['default']
export const LazyProseP: typeof import("../components/content/ProseP.vue")['default']
export const LazyProsePre: typeof import("../components/content/ProsePre.vue")['default']
export const LazyProseStrong: typeof import("../components/content/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../components/content/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../components/content/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../components/content/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../components/content/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../components/content/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../components/content/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../components/content/ProseUl.vue")['default']
export const LazyReadMore: typeof import("../components/content/ReadMore.vue")['default']
export const LazySteps: typeof import("../components/content/Steps.vue")['default']
export const LazyTabs: typeof import("../components/content/Tabs.vue")['default']
export const LazyDarkModeToggle: typeof import("../components/DarkModeToggle.vue")['default']
export const LazyLayoutAside: typeof import("../components/layout/Aside.vue")['default']
export const LazyLayoutAsideTree: typeof import("../components/layout/AsideTree.vue")['default']
export const LazyLayoutAsideTreeItem: typeof import("../components/layout/AsideTreeItem.vue")['default']
export const LazyLayoutBreadcrumb: typeof import("../components/layout/Breadcrumb.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyLayoutHeaderLogo: typeof import("../components/layout/Header/Logo.vue")['default']
export const LazyLayoutHeaderNav: typeof import("../components/layout/Header/Nav.vue")['default']
export const LazyLayoutHeaderNavMobile: typeof import("../components/layout/Header/NavMobile.vue")['default']
export const LazyLayoutHeaderNavMobileItem: typeof import("../components/layout/Header/NavMobileItem.vue")['default']
export const LazyLayoutMobileNav: typeof import("../components/layout/MobileNav.vue")['default']
export const LazyLayoutPrevNext: typeof import("../components/layout/PrevNext.vue")['default']
export const LazyLayoutPrevNextButton: typeof import("../components/layout/PrevNextButton.vue")['default']
export const LazyLayoutSearchButton: typeof import("../components/layout/SearchButton.vue")['default']
export const LazyLayoutSearchDialog: typeof import("../components/layout/SearchDialog.vue")['default']
export const LazyLayoutToc: typeof import("../components/layout/Toc.vue")['default']
export const LazyLayoutTocTree: typeof import("../components/layout/TocTree.vue")['default']
export const LazyUiAlert: typeof import("../components/ui/alert/index")['Alert']
export const LazyUiAlertDescription: typeof import("../components/ui/alert/index")['AlertDescription']
export const LazyUiAlertTitle: typeof import("../components/ui/alert/index")['AlertTitle']
export const LazyUiBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyUiBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyUiBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyUiBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyUiBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyUiBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyUiBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyUiBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyUiButton: typeof import("../components/ui/button/index")['Button']
export const LazyUiCard: typeof import("../components/ui/card/index")['Card']
export const LazyUiCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyUiCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyUiCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyUiCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyUiCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyUiCollapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const LazyUiCollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const LazyUiCollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const LazyUiCommand: typeof import("../components/ui/command/index")['Command']
export const LazyUiCommandDialog: typeof import("../components/ui/command/index")['CommandDialog']
export const LazyUiCommandEmpty: typeof import("../components/ui/command/index")['CommandEmpty']
export const LazyUiCommandGroup: typeof import("../components/ui/command/index")['CommandGroup']
export const LazyUiCommandInput: typeof import("../components/ui/command/index")['CommandInput']
export const LazyUiCommandItem: typeof import("../components/ui/command/index")['CommandItem']
export const LazyUiCommandList: typeof import("../components/ui/command/index")['CommandList']
export const LazyUiCommandSeparator: typeof import("../components/ui/command/index")['CommandSeparator']
export const LazyUiCommandShortcut: typeof import("../components/ui/command/index")['CommandShortcut']
export const LazyUiDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyUiDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyUiDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyUiDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyUiDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyUiDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyUiDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyUiDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyUiDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyUiDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyUiDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyUiDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyUiDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyUiDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyUiDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyUiDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyUiDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyUiDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyUiDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyUiDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyUiDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyUiDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyUiDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyUiNavigationMenu: typeof import("../components/ui/navigation-menu/index")['NavigationMenu']
export const LazyUiNavigationMenuContent: typeof import("../components/ui/navigation-menu/index")['NavigationMenuContent']
export const LazyUiNavigationMenuIndicator: typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuIndicator.vue")['default']
export const LazyUiNavigationMenuItem: typeof import("../components/ui/navigation-menu/index")['NavigationMenuItem']
export const LazyUiNavigationMenuLink: typeof import("../components/ui/navigation-menu/index")['NavigationMenuLink']
export const LazyUiNavigationMenuList: typeof import("../components/ui/navigation-menu/index")['NavigationMenuList']
export const LazyUiNavigationMenuTrigger: typeof import("../components/ui/navigation-menu/index")['NavigationMenuTrigger']
export const LazyUiNavigationMenuViewport: typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/navigation-menu/NavigationMenuViewport.vue")['default']
export const LazyUiScrollArea: typeof import("../components/ui/scroll-area/index")['ScrollArea']
export const LazyUiScrollAreaScrollBar: typeof import("../../../node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/components/ui/scroll-area/ScrollBar.vue")['default']
export const LazyUiSeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazyUiSheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazyUiSheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazyUiSheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazyUiSheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazyUiSheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazyUiSheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazyUiSheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazyUiSheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazyUiTabs: typeof import("../components/ui/tabs/index")['Tabs']
export const LazyUiTabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const LazyUiTabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const LazyUiTabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const LazyContentDoc: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const LazyContentList: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const LazyContentNavigation: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const LazyContentQuery: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const LazyContentRenderer: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const LazyContentRendererMarkdown: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const LazyContentSlot: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const LazyDocumentDrivenEmpty: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const LazyDocumentDrivenNotFound: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const LazyMarkdown: typeof import("../../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.4.1_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_6z2aizzl4o6tqt2aeem7x7h7uy/node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const LazyProseScript: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../../../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyUiDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyUiScrollBar: typeof import("../components/ui/scroll-area/index")['ScrollBar']
export const LazyMDC: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC")['default']
export const LazyMDCRenderer: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer")['default']
export const LazyMDCSlot: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@4.18.0/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot")['default']
export const LazyIcon: typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14_3qzjpbxq6x3urkzmprdl3qn3eq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_t74ig7u57tvsmpuys3qtoolrnu/node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
