// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/florentgiraud/dev/busbud/tailwind-classes-authority/packages/documentation/app.config";
import type { default as appConfig1 } from "/Users/florentgiraud/dev/busbud/tailwind-classes-authority/node_modules/.pnpm/shadcn-docs-nuxt@0.1.3_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@un_gt4qwtyxjkvknromndkpxrlbry/node_modules/shadcn-docs-nuxt/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}