name: Run Commit lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 11
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Print versions
        run: |
          git --version
          node --version
          pnpm --version
          pnpx commitlint --version

      - name: Run commitlint
        env:
          COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
        run: echo $COMMIT_MESSAGE | pnpx commitlint